Improve error checking for git repository

diff --git a/git-notify b/git-notify
--- a/git-notify
+++ b/git-notify
@@ -98,13 +98,14 @@ done
 
 # Test git repository and start execution
 
-if git rev-parse --git-dir > /dev/null 2>&1; then
+if !(git rev-parse --git-dir > /dev/null 2>&1); then
+    echo "Error: not a git repository"
+    exit 1
+else
     if [ $async = true ]; then
         run &
         echo "Started background job with PID $!"
     else
         (run)
     fi
-else
-	echo "Error: not a git repository"
 fi
